// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.ControlMode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
/**
 *
 */
public class Flywheel extends SubsystemBase {
    private WPI_TalonFX flywheelMotor;

    public Flywheel() {
        flywheelMotor = new WPI_TalonFX(5);
        initializeMotors();
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    public void initializeMotors() {
        // reverses the direction of the motors
        flywheelMotor.setInverted(false);
        // specifies unit of measurement
        flywheelMotor.set(ControlMode.PercentOutput, 0);
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void run(double speed, boolean pressed) {
        if (pressed) {
            flywheelMotor.set(ControlMode.PercentOutput, speed);
        } else {
            flywheelMotor.set(ControlMode.PercentOutput, 0);
        }
    }

}
